// components/FinancialScorecard.tsx

import { Card, CardHeader, CardContent, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { Scale } from "lucide-react";

type RatioRating = 'Strong' | 'Neutral' | 'Weak';

interface FinancialScorecardProps {
  ratios: Record<string, { value: string | number, rating: RatioRating }>;
}

const ratingClasses: Record<RatioRating, string> = {
    Strong: "bg-green-500/20 text-green-700 dark:text-green-400 border-green-500/30",
    Neutral: "bg-gray-500/10 text-gray-700 dark:text-gray-400 border-gray-500/20",
    Weak: "bg-red-500/20 text-red-700 dark:text-red-400 border-red-500/30",
};

export function FinancialScorecard({ ratios }: FinancialScorecardProps) {
  // Simple logic to derive an overall rating for the header
  // FIX: Default to empty object if ratios is null/undefined
  const ratioValues = Object.values(ratios || {}); 
  const overallRating = ratioValues.reduce((acc, { rating }) => {
    if (rating === 'Strong') acc.strong++;
    else if (rating === 'Weak') acc.weak++;
    return acc;
  }, { strong: 0, weak: 0 });

  const summaryRating: RatioRating = overallRating.strong > overallRating.weak + 1 ? 'Strong' : overallRating.weak > overallRating.strong ? 'Weak' : 'Neutral';

  return (
    <Card className="border-2 border-border/50">
      <CardHeader className="border-b border-border/50 pb-4 flex-row items-center justify-between">
        <div className="flex items-center gap-3">
            <Scale className="h-6 w-6 text-primary" />
            <CardTitle>Financial Health Scorecard</CardTitle>
        </div>
        <Badge 
            variant="outline"
            className={cn("text-base font-semibold px-3 py-1", ratingClasses[summaryRating])}
        >
            {summaryRating}
        </Badge>
      </CardHeader>
      <CardContent className="pt-6">
        {/* FIX: Also default to empty object in Object.entries */}
        <div className="grid grid-cols-2 gap-x-6 gap-y-6">
          {Object.entries(ratios || {}).map(([key, { value, rating }]) => (
            <div key={key} className="flex flex-col">
              <span className="text-sm text-muted-foreground">{key}</span>
              <div className="flex items-center gap-2">
                <span className="text-lg font-semibold text-foreground">
                  {value}
                </span>
                <Badge 
                    variant="outline"
                    className={cn("text-xs font-medium", ratingClasses[rating])}
                >
                    {rating}
                </Badge>
              </div>
            </div>
          ))}
        </div>
        <CardDescription className="mt-6 text-xs italic">
            Scorecard generated by comparing key company ratios against sector medians. This is a premium feature.
        </CardDescription>
      </CardContent>
    </Card>
  );
}